apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      tier: frontend
      track: stable
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
        track: stable
    spec:
      containers:
      - name: demo
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
